spring:
  application:
    name: dongdong
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    master:
      url: jdbc:mysql://127.0.0.1:3306/dongdong?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=UTF-8
      username: root
      password: 329916
    slave:
      url: jdbc:mysql://127.0.0.1:3306/mobao?useSSL=false&useUnicode=true&autoReconnect=true&characterEncoding=UTF-8
      username: root
      password: 329916
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    content-type: text/html
    cache: false
    mode: LEGACYHTML5
    resources:
      static-locations: classpath:/

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.dongdong.entity.dao

server:
  port: 8900

logging:
  level:
    com.onepro.custom.mapper: DEBUG
